add ios api example
easemob/chat-api-examples pull request #3
Opened 2021-10-08 02:59 UTC by MThrone

2021-10-21 10:24 UTC, Jenniferazeng commented on iOS api-example/README.md
> + - 有效的 Agora 开发者账号
```suggestion
 - 有效的 Agora Chat 开发者账号
```

2021-10-21 10:26 UTC, Jenniferazeng commented on iOS api-example/README.md
> + - iOS 9及以上版本
```suggestion
 - iOS 9 及以上版本
```

2021-10-21 10:27 UTC, Jenniferazeng commented on iOS api-example/README.md
> + ### 1.创建 Agora 项目并获取AppKey
```suggestion
 ### 1.创建 Agora Chat 项目并获取 AppKey
```

2021-10-21 10:28 UTC, Jenniferazeng commented on iOS api-example/README.md
> +**方法 1：使用 pod 方式集成SDK**
```suggestion
**方法 1：使用 pod 方式集成 SDK**
```

2021-10-21 10:28 UTC, Jenniferazeng commented on iOS api-example/README.md
> +创建一个podfile文件，并在podfile里添加相关SDK，示例如下：
```suggestion
创建一个 podfile 文件，并在 podfile 里添加相关 SDK，示例如下：
```

2021-10-21 10:30 UTC, Jenniferazeng commented on iOS api-example/README.md
> +3. 选中项目的 Target，并在 General -> Frameworks,libraries,and... -> 将AgoraChat.framework的“Embed”的选项设置为“Embed & sign”。
```suggestion
3. 选中项目的 Target，并在 General -> Frameworks,libraries,and... -> 将 AgoraChat.framework 的“Embed” 的选项设置为 “Embed & sign”。
```

2021-10-21 10:31 UTC, Jenniferazeng commented on iOS api-example/README.md
> +- 输入会话ID
```suggestion
- 输入会话 ID
```

2021-10-21 10:31 UTC, Jenniferazeng commented on iOS api-example/README.md
> +功能执行结果在页面下半部分会有相关日志记录展示
```suggestion
功能执行结果在页面下半部分会有相关日志记录展示。
```

2021-10-21 10:33 UTC, Jenniferazeng commented on iOS api-example/README.md
> +在终端 Terminal cd到podfile文件所在目录厚执行如下命令集成SDK
```suggestion
在终端 Terminal cd 到 podfile 文件所在目录，执行如下命令集成 SDK。
```

2021-10-22 03:20 UTC, wangjie-agora commented on iOS api-example/README.md
> + ### 1.创建 Agora 项目并获取AppKey
App key 已经在前提条件里了，这个步骤应该要写怎么创建 iOS 项目

2021-10-22 03:28 UTC, wangjie-agora commented on iOS api-example/README.md
> +**方法 1：使用 pod 方式集成SDK**
这边的步骤不够详细，可以参考 https://docs.agora.io/cn/Video/start_call_ios?platform=iOS#方法一：使用-cocoapods-获取-sdk 修改一下

2021-10-22 03:35 UTC, jiewang2 commented on iOS api-example/README.md
> +  	pod 'Masonry'
这个 Masonry 是必须的吗？

2021-10-22 04:15 UTC, jiewang2 commented on iOS api-example/README.md
> +source 'https://github.com/CocoaPods/Specs.git'
写了 source 这行运行 pod install 之后会报错 [!] Couldn't determine repo type for URL: `https://github.com/CocoaPods/Specs.git`: execution expired

2021-10-22 04:36 UTC, wangjie-agora commented on iOS api-example/README.md
> +在项目的 ViewController 文件里添加如下相关代码：
`ViewController.m` 文件

2021-10-22 04:41 UTC, wangjie-agora commented on iOS api-example/README.md
> +#import <AgoraChat/EMOptions+PrivateDeploy.h>
这一行在 Xcode 中报错：`AgoraChat/EMOptions+PrivateDeploy.h' file not found`

2021-10-25 06:37 UTC, Jenniferazeng commented on iOS api-example/README.md
> +在项目的 ViewController 文件里添加如下相关代码：
```suggestion
在项目的 `ViewController.m` 文件里添加如下相关代码：
```

2021-10-27 08:12 UTC, zhangchong-git commented on iOS api-example/README.md
> +  	pod 'Masonry'
这个 readme 不是为了展示如何使用此小 demo嘛，加上就可以直接跑起来

2021-10-27 08:52 UTC, zhangchong-git commented on iOS api-example/README.md
> +#import <AgoraChat/EMOptions+PrivateDeploy.h>
AgoraChat/AgoraChatOptions+PrivateDeploy.h

2021-10-27 08:52 UTC, zhangchong-git commented on iOS api-example/README.md
> +#import <AgoraChat/EMOptions+PrivateDeploy.h>
example 里的sdk已替换为 AgoraChat

2021-10-27 09:09 UTC, Jenniferazeng commented on iOS api-example/README.md
> + ### 1.创建 Agora 项目并获取AppKey
准备开发环境

创建 Xcode 项目

参考以下步骤在 Xcode 中创建一个 iOS 平台下的 Single View App，项目设置如下：

Product Name 设为 AgoraChatQuickstart。
Organization Identifier 设为 agorachat。
User Interface 选择 Storyboard。
Language 选择 Objective-C。

2021-10-27 09:09 UTC, Jenniferazeng commented on iOS api-example/README.md
> +**方法 1：使用 pod 方式集成SDK**
已修改

2021-10-27 09:10 UTC, Jenniferazeng commented on iOS api-example/README.md
> +source 'https://github.com/CocoaPods/Specs.git'
已修改

2021-10-28 03:53 UTC, jiewang2 commented on iOS api-example/README.md
> +@interface ViewController ()<UITextFieldDelegate, UIScrollViewDelegate, EMClientDelegate, EMChatManagerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
这边出现 EM 的地方都要改成 AgoraChat 吧？

2021-10-28 06:51 UTC, Jenniferazeng commented on iOS api-example/README.md
> +// todo 增加跳转链接
```suggestion
```

2021-10-28 06:51 UTC, Jenniferazeng commented on iOS api-example/README.md
> +详情见：//跳转到链接
```suggestion
```

2021-11-01 08:34 UTC, wangjie-agora commented on iOS api-example/README.md
> +    AgoraChatOptions *options = [AgoraChatOptions optionsWithAppkey:@"41351358#427351"];
这边直接写死了 app key，换自己项目的就无法成功登录了？

2021-11-10 10:08 UTC, MThrone commented on iOS api-example/README.md
> +    AgoraChatOptions *options = [AgoraChatOptions optionsWithAppkey:@"41351358#427351"];
为了快速跑起来demo，并且使用007token登陆，，这样就不需要用户自己再搭一个appserver。

2021-11-11 02:58 UTC, wangjie-agora requested changes
还有几个小问题需要修改：
- App 中点完发送消息输入法应该收起来
- 点退出按钮没有任何反应
- 收到消息的日志显示为 send message success, 需要改成 receive a message from xxx:

2022-01-05 12:16 UTC, merged